CREATE DATABASE FishShop_Content;
GO

USE FishShop_Content;
GO

CREATE TABLE dbo.BLOG_CATEGORIES (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Slug NVARCHAR(255) NULL UNIQUE
);

CREATE TABLE dbo.BLOGS (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    CategoryId BIGINT NOT NULL,
    AuthorId BIGINT NULL,
    Title NVARCHAR(255) NOT NULL,
    Slug NVARCHAR(255) NOT NULL UNIQUE,
    Summary NVARCHAR(1000) NULL,
    Content NVARCHAR(MAX) NOT NULL,
    ThumbnailUrl NVARCHAR(1000) NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Draft',
    PublishedAt DATETIME2 NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_BLOGS_BLOG_CATEGORIES FOREIGN KEY (CategoryId) REFERENCES dbo.BLOG_CATEGORIES(Id)
);

CREATE TABLE dbo.CONTACTS (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    FullName NVARCHAR(255) NOT NULL,
    Email NVARCHAR(255) NULL,
    Phone NVARCHAR(30) NULL,
    Subject NVARCHAR(255) NULL,
    Message NVARCHAR(MAX) NOT NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'New',
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
