-- ==========================================================
-- SCHEMA USER DATABASE
-- ==========================================================
USE master;
GO
IF EXISTS (SELECT name FROM sys.databases WHERE name = 'FishShop_User')
BEGIN
    ALTER DATABASE FishShop_User SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE FishShop_User;
END
GO
CREATE DATABASE FishShop_User;
GO

USE FishShop_User;
GO

-- Bảng ROLES
CREATE TABLE dbo.ROLES (
    ID DECIMAL(18,0) IDENTITY(1,1) PRIMARY KEY,
    CODE VARCHAR(30) NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500) NULL,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    UPDATED_AT DATETIME2 DEFAULT SYSUTCDATETIME()
);

-- Bảng USERS
CREATE TABLE dbo.USERS (
    ID DECIMAL(18,0) IDENTITY(1,1) PRIMARY KEY,
    ROLE_ID DECIMAL(18,0) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(150) NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    FULL_NAME VARCHAR(150) NULL,
    PHONE VARCHAR(20) NULL,
    AVATAR_URL VARCHAR(500) NULL,
    STATUS BIT DEFAULT 1,
    IS_ADMIN BIT DEFAULT 0,
    LAST_LOGIN_AT DATETIME2 NULL,
    CREATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    UPDATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    CREATED_BY DECIMAL(18,0) NULL,
    UPDATED_BY DECIMAL(18,0) NULL,
    RESET_TOKEN VARCHAR(200) NULL,
    RESET_TOKEN_EXP DATETIME2 NULL,
    CONSTRAINT FK_USERS_ROLE FOREIGN KEY (ROLE_ID) REFERENCES dbo.ROLES(ID)
);
CREATE INDEX IDX_USERS_ROLE_ID ON dbo.USERS(ROLE_ID);

-- Bảng CUSTOMER_PROFILES
CREATE TABLE dbo.CUSTOMER_PROFILES (
    ID DECIMAL(18,0) IDENTITY(1,1) PRIMARY KEY,
    USER_ID DECIMAL(18,0) NULL UNIQUE,
    CUSTOMER_CODE VARCHAR(30) NOT NULL,
    FULL_NAME VARCHAR(150) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(150) NULL,
    GENDER VARCHAR(10) NULL,
    DATE_OF_BIRTH DATE NULL,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    UPDATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_CUSTOMER_PROFILE_USER FOREIGN KEY (USER_ID) REFERENCES dbo.USERS(ID)
);
CREATE INDEX IDX_CUSTOMER_USER_ID ON dbo.CUSTOMER_PROFILES(USER_ID);

-- Bảng CUSTOMER_ADDRESSES
CREATE TABLE dbo.CUSTOMER_ADDRESSES (
    ID DECIMAL(18,0) IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_ID DECIMAL(18,0) NOT NULL,
    RECEIVER_NAME VARCHAR(150) NOT NULL,
    RECEIVER_PHONE VARCHAR(20) NOT NULL,
    ADDRESS_LINE VARCHAR(255) NOT NULL,
    WARD VARCHAR(100) NULL,
    DISTRICT VARCHAR(100) NOT NULL,
    PROVINCE VARCHAR(100) NOT NULL,
    IS_DEFAULT BIT DEFAULT 0,
    CREATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    UPDATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_CUSTOMER_ADDRESSES_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES dbo.CUSTOMER_PROFILES(ID)
);
CREATE INDEX IDX_CUSTOMER_ADDRESSES_CUSTOMER ON dbo.CUSTOMER_ADDRESSES(CUSTOMER_ID);
