-- ==========================================================
-- SCHEMA PRODUCT DATABASE
-- ==========================================================
USE master;
GO
IF EXISTS (SELECT name FROM sys.databases WHERE name = 'FishShop_Product')
BEGIN
    ALTER DATABASE FishShop_Product SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE FishShop_Product;
END
GO
CREATE DATABASE FishShop_Product;
GO

USE FishShop_Product;
GO

CREATE TABLE dbo.CATEGORIES (
    ID DECIMAL(18,0) IDENTITY(1,1) PRIMARY KEY,
    CATEGORY_CODE VARCHAR(30) NULL,
    NAME VARCHAR(150) NOT NULL,
    SLUG VARCHAR(200) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(1000) NULL,
    IMAGE_URL VARCHAR(500) NULL,
    PARENT_ID DECIMAL(18,0) NULL,
    DISPLAY_ORDER DECIMAL(18,0) DEFAULT 0,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    UPDATED_AT DATETIME2 DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.PRODUCTS (
    ID DECIMAL(18,0) IDENTITY(1,1) PRIMARY KEY,
    CATEGORY_ID DECIMAL(18,0) NOT NULL,
    PRODUCT_CODE VARCHAR(30) NULL,
    SKU VARCHAR(50) NULL,
    NAME VARCHAR(200) NOT NULL,
    SLUG VARCHAR(250) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(MAX) NULL,
    SHORT_DESCRIPTION VARCHAR(500) NULL,
    IMAGE_URL VARCHAR(500) NULL,
    COST_PRICE DECIMAL(18,2) DEFAULT 0,
    SALE_PRICE DECIMAL(18,2) NULL,
    STOCK_QUANTITY DECIMAL(18,0) DEFAULT 0,
    SOLD_QUANTITY DECIMAL(18,0) DEFAULT 0,
    WEIGHT_GRAMS DECIMAL(10,2) NULL,
    IS_FEATURED BIT DEFAULT 0,
    STATUS BIT DEFAULT 1,
    CREATED_BY DECIMAL(18,0) NULL,
    UPDATED_BY DECIMAL(18,0) NULL,
    CREATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    UPDATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_PRODUCTS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES dbo.CATEGORIES(ID)
);
CREATE INDEX IDX_PRODUCTS_CATEGORY_ID ON dbo.PRODUCTS(CATEGORY_ID);

CREATE TABLE dbo.PRODUCT_IMAGES (
    ID DECIMAL(18,0) IDENTITY(1,1) PRIMARY KEY,
    PRODUCT_ID DECIMAL(18,0) NOT NULL,
    IMAGE_URL VARCHAR(500) NOT NULL,
    ALT_TEXT VARCHAR(255) NULL,
    IS_PRIMARY BIT DEFAULT 0,
    DISPLAY_ORDER DECIMAL(18,0) DEFAULT 0,
    CREATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_PRODUCT_IMAGES_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES dbo.PRODUCTS(ID)
);
CREATE INDEX IDX_PRODUCT_IMAGES_PRODUCT_ID ON dbo.PRODUCT_IMAGES(PRODUCT_ID);

CREATE TABLE dbo.INVENTORY (
    PRODUCT_ID DECIMAL(18,0) NOT NULL PRIMARY KEY,
    STOCK_QUANTITY DECIMAL(18,0) DEFAULT 0,
    RESERVED_QUANTITY DECIMAL(18,0) DEFAULT 0,
    WAREHOUSE_LOCATION VARCHAR(255) NULL,
    CREATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    UPDATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_INVENTORY_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES dbo.PRODUCTS(ID)
);

CREATE TABLE dbo.INVENTORY_TRANSACTIONS (
    ID DECIMAL(18,0) IDENTITY(1,1) PRIMARY KEY,
    PRODUCT_ID DECIMAL(18,0) NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    QUANTITY DECIMAL(18,0) NOT NULL,
    REFERENCE_TYPE VARCHAR(50) NULL,
    REFERENCE_ID DECIMAL(18,0) NULL,
    CREATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_INVENTORY_TRANSACTIONS_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES dbo.PRODUCTS(ID)
);
