CREATE DATABASE FishShop_Product;
GO

USE FishShop_Product;
GO

CREATE TABLE dbo.CATEGORIES (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Slug NVARCHAR(255) NOT NULL UNIQUE,
    Description NVARCHAR(MAX) NULL,
    Status BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.PRODUCTS (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    CategoryId BIGINT NOT NULL,
    Name NVARCHAR(255) NOT NULL,
    Slug NVARCHAR(255) NOT NULL UNIQUE,
    Price DECIMAL(18,2) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    ThumbImage NVARCHAR(1000) NULL,
    Status BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_PRODUCTS_CATEGORIES FOREIGN KEY (CategoryId) REFERENCES dbo.CATEGORIES(Id)
);

CREATE TABLE dbo.PRODUCT_IMAGES (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    ProductId BIGINT NOT NULL,
    ImageUrl NVARCHAR(1000) NOT NULL,
    PublicId NVARCHAR(500) NULL,
    IsMain BIT NOT NULL DEFAULT 0,
    DisplayOrder INT NOT NULL DEFAULT 0,
    CONSTRAINT FK_PRODUCT_IMAGES_PRODUCTS FOREIGN KEY (ProductId) REFERENCES dbo.PRODUCTS(Id)
);

CREATE TABLE dbo.INVENTORY (
    ProductId BIGINT NOT NULL PRIMARY KEY,
    StockQuantity INT NOT NULL DEFAULT 0,
    ReservedQuantity INT NOT NULL DEFAULT 0,
    WarehouseLocation NVARCHAR(255) NULL,
    CONSTRAINT FK_INVENTORY_PRODUCTS FOREIGN KEY (ProductId) REFERENCES dbo.PRODUCTS(Id)
);

CREATE TABLE dbo.INVENTORY_TRANSACTIONS (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    ProductId BIGINT NOT NULL,
    Type NVARCHAR(50) NOT NULL,
    Quantity INT NOT NULL,
    ReferenceType NVARCHAR(50) NULL,
    ReferenceId BIGINT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_INVENTORY_TRANSACTIONS_PRODUCTS FOREIGN KEY (ProductId) REFERENCES dbo.PRODUCTS(Id)
);
