-- ==========================================================
-- SCHEMA CONTENT DATABASE
-- ==========================================================
USE master;
GO
IF EXISTS (SELECT name FROM sys.databases WHERE name = 'FishShop_Content')
BEGIN
    ALTER DATABASE FishShop_Content SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE FishShop_Content;
END
GO
CREATE DATABASE FishShop_Content;
GO

USE FishShop_Content;
GO

CREATE TABLE dbo.BLOG_CATEGORIES (
    ID DECIMAL(18,0) IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL,
    SLUG VARCHAR(200) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(500) NULL,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    UPDATED_AT DATETIME2 DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.BLOG_POSTS (
    ID DECIMAL(18,0) IDENTITY(1,1) PRIMARY KEY,
    CATEGORY_ID DECIMAL(18,0) NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    SLUG VARCHAR(250) NOT NULL UNIQUE,
    SUMMARY VARCHAR(500) NULL,
    CONTENT VARCHAR(MAX) NULL,
    THUMBNAIL_URL VARCHAR(500) NULL,
    AUTHOR_ID DECIMAL(18,0) NULL,
    PUBLISHED_AT DATETIME2 NULL,
    STATUS VARCHAR(20) DEFAULT 'DRAFT',
    CREATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    UPDATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_BLOG_POSTS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES dbo.BLOG_CATEGORIES(ID)
);
CREATE INDEX IDX_BLOG_POSTS_CATEGORY_ID ON dbo.BLOG_POSTS(CATEGORY_ID);

CREATE TABLE dbo.CONTACT_MESSAGES (
    ID DECIMAL(18,0) IDENTITY(1,1) PRIMARY KEY,
    FULL_NAME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) NULL,
    PHONE VARCHAR(20) NULL,
    SUBJECT VARCHAR(200) NULL,
    MESSAGE VARCHAR(MAX) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'NEW',
    CREATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    UPDATED_AT DATETIME2 DEFAULT SYSUTCDATETIME()
);
