-- ==========================================================
-- SCHEMA ORDER DATABASE
-- ==========================================================
USE master;
GO
IF EXISTS (SELECT name FROM sys.databases WHERE name = 'FishShop_Order')
BEGIN
    ALTER DATABASE FishShop_Order SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE FishShop_Order;
END
GO
CREATE DATABASE FishShop_Order;
GO

USE FishShop_Order;
GO

CREATE TABLE dbo.SHOPPING_CARTS (
    ID DECIMAL(18,0) IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_ID DECIMAL(18,0) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    UPDATED_AT DATETIME2 DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.CART_ITEMS (
    ID DECIMAL(18,0) IDENTITY(1,1) PRIMARY KEY,
    CART_ID DECIMAL(18,0) NOT NULL,
    PRODUCT_ID DECIMAL(18,0) NOT NULL,
    PRODUCT_NAME NVARCHAR(250) NULL,
    IMAGE_URL NVARCHAR(500) NULL,
    QUANTITY DECIMAL(18,0) NOT NULL,
    UNIT_PRICE DECIMAL(18,2) NOT NULL,
    CREATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    UPDATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_CART_ITEMS_CARTS FOREIGN KEY (CART_ID) REFERENCES dbo.SHOPPING_CARTS(ID)
);

CREATE TABLE dbo.ORDERS (
    ID DECIMAL(18,0) IDENTITY(1,1) PRIMARY KEY,
    ORDER_CODE VARCHAR(30) NOT NULL UNIQUE,
    CUSTOMER_ID DECIMAL(18,0) NULL,
    CUSTOMER_NAME VARCHAR(150) NULL,
    CUSTOMER_PHONE VARCHAR(20) NULL,
    CUSTOMER_EMAIL VARCHAR(150) NULL,
    CUSTOMER_ADDRESS VARCHAR(500) NULL,
    ADDRESS_ID DECIMAL(18,0) NULL,
    SUBTOTAL_AMOUNT DECIMAL(18,2) DEFAULT 0,
    DISCOUNT_AMOUNT DECIMAL(18,2) DEFAULT 0,
    SHIPPING_FEE DECIMAL(18,2) DEFAULT 0,
    TOTAL_AMOUNT DECIMAL(18,2) DEFAULT 0,
    PROMOTION_ID DECIMAL(18,0) NULL,
    PAYMENT_METHOD VARCHAR(20) DEFAULT 'COD',
    PAYMENT_STATUS VARCHAR(20) DEFAULT 'UNPAID',
    ORDER_STATUS VARCHAR(20) DEFAULT 'PENDING',
    ORDER_SOURCE VARCHAR(20) DEFAULT 'ONLINE',
    NOTE VARCHAR(1000) NULL,
    CONFIRMED_AT DATETIME2 NULL,
    SHIPPED_AT DATETIME2 NULL,
    DELIVERED_AT DATETIME2 NULL,
    CANCELLED_AT DATETIME2 NULL,
    CREATED_BY DECIMAL(18,0) NULL,
    CREATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    UPDATED_AT DATETIME2 DEFAULT SYSUTCDATETIME()
);
CREATE INDEX IDX_ORDERS_CUSTOMER_ID ON dbo.ORDERS(CUSTOMER_ID);
CREATE INDEX IDX_ORDERS_STATUS ON dbo.ORDERS(ORDER_STATUS);

CREATE TABLE dbo.ORDER_ITEMS (
    ID              DECIMAL(18,0)  IDENTITY(1,1) PRIMARY KEY,
    ORDER_ID        DECIMAL(18,0)  NOT NULL,
    PRODUCT_ID      DECIMAL(18,0)  NOT NULL,
    PRODUCT_NAME    NVARCHAR(250)  NULL,
    SKU             VARCHAR(50)    NULL,
    IMAGE_URL       NVARCHAR(500)  NULL,
    UNIT_PRICE      DECIMAL(18,2)  NOT NULL,
    QUANTITY        DECIMAL(18,0)  NOT NULL,
    DISCOUNT_AMOUNT DECIMAL(18,2)  DEFAULT 0,
    LINE_TOTAL      DECIMAL(18,2)  NOT NULL,
    CREATED_AT      DATETIME2      DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_ORDER_ITEMS_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES dbo.ORDERS(ID)
);

CREATE TABLE dbo.PAYMENTS (
    ID DECIMAL(18,0) IDENTITY(1,1) PRIMARY KEY,
    ORDER_ID DECIMAL(18,0) NOT NULL,
    PAYMENT_CODE VARCHAR(30) NOT NULL UNIQUE,
    METHOD VARCHAR(20) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    AMOUNT DECIMAL(18,2) NOT NULL,
    TRANSACTION_REF VARCHAR(100) NULL,
    PAID_AT DATETIME2 NULL,
    NOTE VARCHAR(500) NULL,
    CREATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    UPDATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_PAYMENTS_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES dbo.ORDERS(ID)
);

CREATE TABLE dbo.PROMOTIONS (
    ID DECIMAL(18,0) IDENTITY(1,1) PRIMARY KEY,
    PROMO_CODE VARCHAR(30) NOT NULL UNIQUE,
    TITLE VARCHAR(150) NOT NULL,
    DESCRIPTION VARCHAR(1000) NULL,
    DISCOUNT_TYPE VARCHAR(20) NOT NULL,
    DISCOUNT_VALUE DECIMAL(18,2) NOT NULL,
    MIN_ORDER_VALUE DECIMAL(18,2) DEFAULT 0,
    MAX_DISCOUNT_VALUE DECIMAL(18,2) NULL,
    START_AT DATETIME2 NOT NULL,
    END_AT DATETIME2 NOT NULL,
    USAGE_LIMIT DECIMAL(18,0) NULL,
    USED_COUNT DECIMAL(18,0) DEFAULT 0,
    STATUS BIT DEFAULT 1,
    CREATED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    UPDATED_AT DATETIME2 DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.PROMOTION_PRODUCTS (
    ID DECIMAL(18,0) IDENTITY(1,1) PRIMARY KEY,
    PROMOTION_ID DECIMAL(18,0) NOT NULL,
    PRODUCT_ID DECIMAL(18,0) NOT NULL,
    CONSTRAINT FK_PROMOTION_PRODUCTS_PROMOTIONS FOREIGN KEY (PROMOTION_ID) REFERENCES dbo.PROMOTIONS(ID)
);

CREATE TABLE dbo.PROMOTION_USAGES (
    ID DECIMAL(18,0) IDENTITY(1,1) PRIMARY KEY,
    PROMOTION_ID DECIMAL(18,0) NOT NULL,
    ORDER_ID DECIMAL(18,0) NOT NULL,
    CUSTOMER_ID DECIMAL(18,0) NULL,
    USED_AT DATETIME2 DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_PROMOTION_USAGES_PROMOTIONS FOREIGN KEY (PROMOTION_ID) REFERENCES dbo.PROMOTIONS(ID),
    CONSTRAINT FK_PROMOTION_USAGES_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES dbo.ORDERS(ID)
);
