CREATE DATABASE FishShop_User;
GO

USE FishShop_User;
GO

CREATE TABLE dbo.USERS (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(500) NOT NULL,
    Email NVARCHAR(255) NULL,
    Phone NVARCHAR(30) NULL,
    Status BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.ROLES (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    Code NVARCHAR(50) NOT NULL UNIQUE,
    Name NVARCHAR(100) NOT NULL
);

CREATE TABLE dbo.USER_ROLES (
    UserId BIGINT NOT NULL,
    RoleId BIGINT NOT NULL,
    CONSTRAINT PK_USER_ROLES PRIMARY KEY (UserId, RoleId),
    CONSTRAINT FK_USER_ROLES_USERS FOREIGN KEY (UserId) REFERENCES dbo.USERS(Id),
    CONSTRAINT FK_USER_ROLES_ROLES FOREIGN KEY (RoleId) REFERENCES dbo.ROLES(Id)
);

CREATE TABLE dbo.PROFILES (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    UserId BIGINT NOT NULL UNIQUE,
    FullName NVARCHAR(255) NULL,
    AvatarUrl NVARCHAR(1000) NULL,
    Gender NVARCHAR(20) NULL,
    DateOfBirth DATE NULL,
    CONSTRAINT FK_PROFILES_USERS FOREIGN KEY (UserId) REFERENCES dbo.USERS(Id)
);

CREATE TABLE dbo.ADDRESSES (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    UserId BIGINT NOT NULL,
    ReceiverName NVARCHAR(255) NOT NULL,
    ReceiverPhone NVARCHAR(30) NOT NULL,
    Province NVARCHAR(100) NULL,
    District NVARCHAR(100) NULL,
    Ward NVARCHAR(100) NULL,
    AddressLine NVARCHAR(500) NOT NULL,
    IsDefault BIT NOT NULL DEFAULT 0,
    CONSTRAINT FK_ADDRESSES_USERS FOREIGN KEY (UserId) REFERENCES dbo.USERS(Id)
);
