CREATE DATABASE FishShop_Order;
GO

USE FishShop_Order;
GO

CREATE TABLE dbo.CARTS (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    UserId BIGINT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.CART_ITEMS (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    CartId BIGINT NOT NULL,
    ProductId BIGINT NOT NULL,
    Quantity INT NOT NULL,
    CONSTRAINT FK_CART_ITEMS_CARTS FOREIGN KEY (CartId) REFERENCES dbo.CARTS(Id)
);

CREATE TABLE dbo.ORDERS (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    OrderCode NVARCHAR(50) NOT NULL UNIQUE,
    UserId BIGINT NULL,
    OrderDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CustomerName NVARCHAR(255) NOT NULL,
    CustomerPhone NVARCHAR(30) NOT NULL,
    ShippingAddress NVARCHAR(500) NOT NULL,
    TotalAmount DECIMAL(18,2) NOT NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'New',
    Note NVARCHAR(1000) NULL
);

CREATE TABLE dbo.ORDER_ITEMS (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    OrderId BIGINT NOT NULL,
    ProductId BIGINT NOT NULL,
    ProductName NVARCHAR(255) NOT NULL,
    UnitPrice DECIMAL(18,2) NOT NULL,
    Quantity INT NOT NULL,
    CONSTRAINT FK_ORDER_ITEMS_ORDERS FOREIGN KEY (OrderId) REFERENCES dbo.ORDERS(Id)
);

CREATE TABLE dbo.PAYMENTS (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    OrderId BIGINT NOT NULL,
    PaymentMethod NVARCHAR(50) NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Pending',
    TransactionCode NVARCHAR(255) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_PAYMENTS_ORDERS FOREIGN KEY (OrderId) REFERENCES dbo.ORDERS(Id)
);

CREATE TABLE dbo.PROMOTIONS (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    Code NVARCHAR(50) NOT NULL UNIQUE,
    DiscountType NVARCHAR(20) NOT NULL,
    DiscountValue DECIMAL(18,2) NOT NULL,
    StartDate DATETIME2 NOT NULL,
    EndDate DATETIME2 NOT NULL,
    Status BIT NOT NULL DEFAULT 1
);

CREATE TABLE dbo.PROMOTION_USAGES (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    PromotionId BIGINT NOT NULL,
    OrderId BIGINT NOT NULL,
    UserId BIGINT NULL,
    UsedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_PROMOTION_USAGES_PROMOTIONS FOREIGN KEY (PromotionId) REFERENCES dbo.PROMOTIONS(Id),
    CONSTRAINT FK_PROMOTION_USAGES_ORDERS FOREIGN KEY (OrderId) REFERENCES dbo.ORDERS(Id)
);
