global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: fishshop-gateway
    metrics_path: /metrics
    static_configs:
      - targets:
          - fishshop-gateway:8080
        labels:
          service: Gateway

  - job_name: api-user
    metrics_path: /metrics
    static_configs:
      - targets:
          - api-user:8080
        labels:
          service: API.User

  - job_name: api-product
    metrics_path: /metrics
    static_configs:
      - targets:
          - api-product:8080
        labels:
          service: API.Product

  - job_name: api-order
    metrics_path: /metrics
    static_configs:
      - targets:
          - api-order:8080
        labels:
          service: API.Order

  - job_name: api-content
    metrics_path: /metrics
    static_configs:
      - targets:
          - api-content:8080
        labels:
          service: API.Content

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
